/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as V2OnboardRouteImport } from './routes/v2/onboard'
import { Route as V2GeneralLayoutRouteImport } from './routes/v2/_generalLayout'
import { Route as V2Appv2LayoutRouteImport } from './routes/v2/_appv2Layout'
import { Route as DotwellKnownFarcasterDotjsonRouteImport } from './routes/[.]well-known/farcaster[.]json'
import { Route as appProviderRouteRouteImport } from './routes/(app)/_provider/route'
import { Route as V2Appv2LayoutIndexRouteImport } from './routes/v2/_appv2Layout.index'
import { Route as V2QuizQuizIdRouteImport } from './routes/v2/quiz/$quizId'
import { Route as V2GeneralLayoutProfileRouteImport } from './routes/v2/_generalLayout.profile'
import { Route as V2GeneralLayoutPrivacyRouteImport } from './routes/v2/_generalLayout.privacy'
import { Route as V2GeneralLayoutNetworkRouteImport } from './routes/v2/_generalLayout.network'
import { Route as V2GeneralLayoutFaqRouteImport } from './routes/v2/_generalLayout.faq'
import { Route as V2GeneralLayoutAboutRouteImport } from './routes/v2/_generalLayout.about'
import { Route as V2Appv2LayoutCollectionRouteImport } from './routes/v2/_appv2Layout.collection'
import { Route as V2Appv2LayoutAccountRouteImport } from './routes/v2/_appv2Layout.account'
import { Route as ApiAiCompleteTestRouteImport } from './routes/api/ai/complete-test'
import { Route as deprecatedLegacyAppRouteImport } from './routes/(deprecated)/legacy/_app'
import { Route as appProviderOnboardRouteImport } from './routes/(app)/_provider/onboard'
import { Route as appProviderGeneralRouteRouteImport } from './routes/(app)/_provider/_general/route'
import { Route as appProviderAppRouteRouteImport } from './routes/(app)/_provider/_app/route'
import { Route as deprecatedLegacyAppIndexRouteImport } from './routes/(deprecated)/legacy/_app/index'
import { Route as appProviderAppIndexRouteImport } from './routes/(app)/_provider/_app/index'
import { Route as appProviderGeneralProfileRouteImport } from './routes/(app)/_provider/_general/profile'
import { Route as appProviderGeneralPrivacyRouteImport } from './routes/(app)/_provider/_general/privacy'
import { Route as appProviderGeneralNetworkRouteImport } from './routes/(app)/_provider/_general/network'
import { Route as appProviderGeneralFaqRouteImport } from './routes/(app)/_provider/_general/faq'
import { Route as appProviderGeneralAboutRouteImport } from './routes/(app)/_provider/_general/about'
import { Route as deprecatedLegacyAppCollectionIndexRouteImport } from './routes/(deprecated)/legacy/_app/collection/index'
import { Route as deprecatedLegacyAppBrowseIndexRouteImport } from './routes/(deprecated)/legacy/_app/browse/index'
import { Route as deprecatedLegacyAppAccountIndexRouteImport } from './routes/(deprecated)/legacy/_app/account/index'
import { Route as appProviderAppCollectionIndexRouteImport } from './routes/(app)/_provider/_app/collection/index'
import { Route as appProviderAppAccountIndexRouteImport } from './routes/(app)/_provider/_app/account/index'
import { Route as deprecatedLegacyAppTakeQuizQuizIdRouteImport } from './routes/(deprecated)/legacy/_app/take-quiz/$quizId'
import { Route as appProviderAppQuizQuizIdRouteImport } from './routes/(app)/_provider/_app/quiz/$quizId'

const V2RouteImport = createFileRoute('/v2')()
const appRouteImport = createFileRoute('/(app)')()
const deprecatedLegacyRouteImport = createFileRoute('/(deprecated)/legacy')()

const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const appRoute = appRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const deprecatedLegacyRoute = deprecatedLegacyRouteImport.update({
  id: '/(deprecated)/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const V2OnboardRoute = V2OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => V2Route,
} as any)
const V2GeneralLayoutRoute = V2GeneralLayoutRouteImport.update({
  id: '/_generalLayout',
  getParentRoute: () => V2Route,
} as any)
const V2Appv2LayoutRoute = V2Appv2LayoutRouteImport.update({
  id: '/_appv2Layout',
  getParentRoute: () => V2Route,
} as any)
const DotwellKnownFarcasterDotjsonRoute =
  DotwellKnownFarcasterDotjsonRouteImport.update({
    id: '/.well-known/farcaster.json',
    path: '/.well-known/farcaster.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const appProviderRouteRoute = appProviderRouteRouteImport.update({
  id: '/_provider',
  getParentRoute: () => appRoute,
} as any)
const V2Appv2LayoutIndexRoute = V2Appv2LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => V2Appv2LayoutRoute,
} as any)
const V2QuizQuizIdRoute = V2QuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => V2Route,
} as any)
const V2GeneralLayoutProfileRoute = V2GeneralLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => V2GeneralLayoutRoute,
} as any)
const V2GeneralLayoutPrivacyRoute = V2GeneralLayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => V2GeneralLayoutRoute,
} as any)
const V2GeneralLayoutNetworkRoute = V2GeneralLayoutNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => V2GeneralLayoutRoute,
} as any)
const V2GeneralLayoutFaqRoute = V2GeneralLayoutFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => V2GeneralLayoutRoute,
} as any)
const V2GeneralLayoutAboutRoute = V2GeneralLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => V2GeneralLayoutRoute,
} as any)
const V2Appv2LayoutCollectionRoute = V2Appv2LayoutCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => V2Appv2LayoutRoute,
} as any)
const V2Appv2LayoutAccountRoute = V2Appv2LayoutAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => V2Appv2LayoutRoute,
} as any)
const ApiAiCompleteTestRoute = ApiAiCompleteTestRouteImport.update({
  id: '/api/ai/complete-test',
  path: '/api/ai/complete-test',
  getParentRoute: () => rootRouteImport,
} as any)
const deprecatedLegacyAppRoute = deprecatedLegacyAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => deprecatedLegacyRoute,
} as any)
const appProviderOnboardRoute = appProviderOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => appProviderRouteRoute,
} as any)
const appProviderGeneralRouteRoute = appProviderGeneralRouteRouteImport.update({
  id: '/_general',
  getParentRoute: () => appProviderRouteRoute,
} as any)
const appProviderAppRouteRoute = appProviderAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => appProviderRouteRoute,
} as any)
const deprecatedLegacyAppIndexRoute =
  deprecatedLegacyAppIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => deprecatedLegacyAppRoute,
  } as any)
const appProviderAppIndexRoute = appProviderAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appProviderAppRouteRoute,
} as any)
const appProviderGeneralProfileRoute =
  appProviderGeneralProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => appProviderGeneralRouteRoute,
  } as any)
const appProviderGeneralPrivacyRoute =
  appProviderGeneralPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => appProviderGeneralRouteRoute,
  } as any)
const appProviderGeneralNetworkRoute =
  appProviderGeneralNetworkRouteImport.update({
    id: '/network',
    path: '/network',
    getParentRoute: () => appProviderGeneralRouteRoute,
  } as any)
const appProviderGeneralFaqRoute = appProviderGeneralFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => appProviderGeneralRouteRoute,
} as any)
const appProviderGeneralAboutRoute = appProviderGeneralAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => appProviderGeneralRouteRoute,
} as any)
const deprecatedLegacyAppCollectionIndexRoute =
  deprecatedLegacyAppCollectionIndexRouteImport.update({
    id: '/collection/',
    path: '/collection/',
    getParentRoute: () => deprecatedLegacyAppRoute,
  } as any)
const deprecatedLegacyAppBrowseIndexRoute =
  deprecatedLegacyAppBrowseIndexRouteImport.update({
    id: '/browse/',
    path: '/browse/',
    getParentRoute: () => deprecatedLegacyAppRoute,
  } as any)
const deprecatedLegacyAppAccountIndexRoute =
  deprecatedLegacyAppAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => deprecatedLegacyAppRoute,
  } as any)
const appProviderAppCollectionIndexRoute =
  appProviderAppCollectionIndexRouteImport.update({
    id: '/collection/',
    path: '/collection/',
    getParentRoute: () => appProviderAppRouteRoute,
  } as any)
const appProviderAppAccountIndexRoute =
  appProviderAppAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => appProviderAppRouteRoute,
  } as any)
const deprecatedLegacyAppTakeQuizQuizIdRoute =
  deprecatedLegacyAppTakeQuizQuizIdRouteImport.update({
    id: '/take-quiz/$quizId',
    path: '/take-quiz/$quizId',
    getParentRoute: () => deprecatedLegacyAppRoute,
  } as any)
const appProviderAppQuizQuizIdRoute =
  appProviderAppQuizQuizIdRouteImport.update({
    id: '/quiz/$quizId',
    path: '/quiz/$quizId',
    getParentRoute: () => appProviderAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof appProviderAppIndexRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/v2': typeof V2GeneralLayoutRouteWithChildren
  '/v2/onboard': typeof V2OnboardRoute
  '/onboard': typeof appProviderOnboardRoute
  '/legacy': typeof deprecatedLegacyAppRouteWithChildren
  '/api/ai/complete-test': typeof ApiAiCompleteTestRoute
  '/v2/account': typeof V2Appv2LayoutAccountRoute
  '/v2/collection': typeof V2Appv2LayoutCollectionRoute
  '/v2/about': typeof V2GeneralLayoutAboutRoute
  '/v2/faq': typeof V2GeneralLayoutFaqRoute
  '/v2/network': typeof V2GeneralLayoutNetworkRoute
  '/v2/privacy': typeof V2GeneralLayoutPrivacyRoute
  '/v2/profile': typeof V2GeneralLayoutProfileRoute
  '/v2/quiz/$quizId': typeof V2QuizQuizIdRoute
  '/v2/': typeof V2Appv2LayoutIndexRoute
  '/about': typeof appProviderGeneralAboutRoute
  '/faq': typeof appProviderGeneralFaqRoute
  '/network': typeof appProviderGeneralNetworkRoute
  '/privacy': typeof appProviderGeneralPrivacyRoute
  '/profile': typeof appProviderGeneralProfileRoute
  '/legacy/': typeof deprecatedLegacyAppIndexRoute
  '/quiz/$quizId': typeof appProviderAppQuizQuizIdRoute
  '/legacy/take-quiz/$quizId': typeof deprecatedLegacyAppTakeQuizQuizIdRoute
  '/account': typeof appProviderAppAccountIndexRoute
  '/collection': typeof appProviderAppCollectionIndexRoute
  '/legacy/account': typeof deprecatedLegacyAppAccountIndexRoute
  '/legacy/browse': typeof deprecatedLegacyAppBrowseIndexRoute
  '/legacy/collection': typeof deprecatedLegacyAppCollectionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof appProviderAppIndexRoute
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/v2': typeof V2Appv2LayoutIndexRoute
  '/v2/onboard': typeof V2OnboardRoute
  '/onboard': typeof appProviderOnboardRoute
  '/legacy': typeof deprecatedLegacyAppIndexRoute
  '/api/ai/complete-test': typeof ApiAiCompleteTestRoute
  '/v2/account': typeof V2Appv2LayoutAccountRoute
  '/v2/collection': typeof V2Appv2LayoutCollectionRoute
  '/v2/about': typeof V2GeneralLayoutAboutRoute
  '/v2/faq': typeof V2GeneralLayoutFaqRoute
  '/v2/network': typeof V2GeneralLayoutNetworkRoute
  '/v2/privacy': typeof V2GeneralLayoutPrivacyRoute
  '/v2/profile': typeof V2GeneralLayoutProfileRoute
  '/v2/quiz/$quizId': typeof V2QuizQuizIdRoute
  '/about': typeof appProviderGeneralAboutRoute
  '/faq': typeof appProviderGeneralFaqRoute
  '/network': typeof appProviderGeneralNetworkRoute
  '/privacy': typeof appProviderGeneralPrivacyRoute
  '/profile': typeof appProviderGeneralProfileRoute
  '/quiz/$quizId': typeof appProviderAppQuizQuizIdRoute
  '/legacy/take-quiz/$quizId': typeof deprecatedLegacyAppTakeQuizQuizIdRoute
  '/account': typeof appProviderAppAccountIndexRoute
  '/collection': typeof appProviderAppCollectionIndexRoute
  '/legacy/account': typeof deprecatedLegacyAppAccountIndexRoute
  '/legacy/browse': typeof deprecatedLegacyAppBrowseIndexRoute
  '/legacy/collection': typeof deprecatedLegacyAppCollectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteWithChildren
  '/(app)/_provider': typeof appProviderRouteRouteWithChildren
  '/.well-known/farcaster.json': typeof DotwellKnownFarcasterDotjsonRoute
  '/v2': typeof V2RouteWithChildren
  '/v2/_appv2Layout': typeof V2Appv2LayoutRouteWithChildren
  '/v2/_generalLayout': typeof V2GeneralLayoutRouteWithChildren
  '/v2/onboard': typeof V2OnboardRoute
  '/(app)/_provider/_app': typeof appProviderAppRouteRouteWithChildren
  '/(app)/_provider/_general': typeof appProviderGeneralRouteRouteWithChildren
  '/(app)/_provider/onboard': typeof appProviderOnboardRoute
  '/(deprecated)/legacy': typeof deprecatedLegacyRouteWithChildren
  '/(deprecated)/legacy/_app': typeof deprecatedLegacyAppRouteWithChildren
  '/api/ai/complete-test': typeof ApiAiCompleteTestRoute
  '/v2/_appv2Layout/account': typeof V2Appv2LayoutAccountRoute
  '/v2/_appv2Layout/collection': typeof V2Appv2LayoutCollectionRoute
  '/v2/_generalLayout/about': typeof V2GeneralLayoutAboutRoute
  '/v2/_generalLayout/faq': typeof V2GeneralLayoutFaqRoute
  '/v2/_generalLayout/network': typeof V2GeneralLayoutNetworkRoute
  '/v2/_generalLayout/privacy': typeof V2GeneralLayoutPrivacyRoute
  '/v2/_generalLayout/profile': typeof V2GeneralLayoutProfileRoute
  '/v2/quiz/$quizId': typeof V2QuizQuizIdRoute
  '/v2/_appv2Layout/': typeof V2Appv2LayoutIndexRoute
  '/(app)/_provider/_general/about': typeof appProviderGeneralAboutRoute
  '/(app)/_provider/_general/faq': typeof appProviderGeneralFaqRoute
  '/(app)/_provider/_general/network': typeof appProviderGeneralNetworkRoute
  '/(app)/_provider/_general/privacy': typeof appProviderGeneralPrivacyRoute
  '/(app)/_provider/_general/profile': typeof appProviderGeneralProfileRoute
  '/(app)/_provider/_app/': typeof appProviderAppIndexRoute
  '/(deprecated)/legacy/_app/': typeof deprecatedLegacyAppIndexRoute
  '/(app)/_provider/_app/quiz/$quizId': typeof appProviderAppQuizQuizIdRoute
  '/(deprecated)/legacy/_app/take-quiz/$quizId': typeof deprecatedLegacyAppTakeQuizQuizIdRoute
  '/(app)/_provider/_app/account/': typeof appProviderAppAccountIndexRoute
  '/(app)/_provider/_app/collection/': typeof appProviderAppCollectionIndexRoute
  '/(deprecated)/legacy/_app/account/': typeof deprecatedLegacyAppAccountIndexRoute
  '/(deprecated)/legacy/_app/browse/': typeof deprecatedLegacyAppBrowseIndexRoute
  '/(deprecated)/legacy/_app/collection/': typeof deprecatedLegacyAppCollectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/.well-known/farcaster.json'
    | '/v2'
    | '/v2/onboard'
    | '/onboard'
    | '/legacy'
    | '/api/ai/complete-test'
    | '/v2/account'
    | '/v2/collection'
    | '/v2/about'
    | '/v2/faq'
    | '/v2/network'
    | '/v2/privacy'
    | '/v2/profile'
    | '/v2/quiz/$quizId'
    | '/v2/'
    | '/about'
    | '/faq'
    | '/network'
    | '/privacy'
    | '/profile'
    | '/legacy/'
    | '/quiz/$quizId'
    | '/legacy/take-quiz/$quizId'
    | '/account'
    | '/collection'
    | '/legacy/account'
    | '/legacy/browse'
    | '/legacy/collection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/.well-known/farcaster.json'
    | '/v2'
    | '/v2/onboard'
    | '/onboard'
    | '/legacy'
    | '/api/ai/complete-test'
    | '/v2/account'
    | '/v2/collection'
    | '/v2/about'
    | '/v2/faq'
    | '/v2/network'
    | '/v2/privacy'
    | '/v2/profile'
    | '/v2/quiz/$quizId'
    | '/about'
    | '/faq'
    | '/network'
    | '/privacy'
    | '/profile'
    | '/quiz/$quizId'
    | '/legacy/take-quiz/$quizId'
    | '/account'
    | '/collection'
    | '/legacy/account'
    | '/legacy/browse'
    | '/legacy/collection'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/_provider'
    | '/.well-known/farcaster.json'
    | '/v2'
    | '/v2/_appv2Layout'
    | '/v2/_generalLayout'
    | '/v2/onboard'
    | '/(app)/_provider/_app'
    | '/(app)/_provider/_general'
    | '/(app)/_provider/onboard'
    | '/(deprecated)/legacy'
    | '/(deprecated)/legacy/_app'
    | '/api/ai/complete-test'
    | '/v2/_appv2Layout/account'
    | '/v2/_appv2Layout/collection'
    | '/v2/_generalLayout/about'
    | '/v2/_generalLayout/faq'
    | '/v2/_generalLayout/network'
    | '/v2/_generalLayout/privacy'
    | '/v2/_generalLayout/profile'
    | '/v2/quiz/$quizId'
    | '/v2/_appv2Layout/'
    | '/(app)/_provider/_general/about'
    | '/(app)/_provider/_general/faq'
    | '/(app)/_provider/_general/network'
    | '/(app)/_provider/_general/privacy'
    | '/(app)/_provider/_general/profile'
    | '/(app)/_provider/_app/'
    | '/(deprecated)/legacy/_app/'
    | '/(app)/_provider/_app/quiz/$quizId'
    | '/(deprecated)/legacy/_app/take-quiz/$quizId'
    | '/(app)/_provider/_app/account/'
    | '/(app)/_provider/_app/collection/'
    | '/(deprecated)/legacy/_app/account/'
    | '/(deprecated)/legacy/_app/browse/'
    | '/(deprecated)/legacy/_app/collection/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRoute: typeof appRouteWithChildren
  DotwellKnownFarcasterDotjsonRoute: typeof DotwellKnownFarcasterDotjsonRoute
  V2Route: typeof V2RouteWithChildren
  deprecatedLegacyRoute: typeof deprecatedLegacyRouteWithChildren
  ApiAiCompleteTestRoute: typeof ApiAiCompleteTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(deprecated)/legacy': {
      id: '/(deprecated)/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof deprecatedLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/onboard': {
      id: '/v2/onboard'
      path: '/onboard'
      fullPath: '/v2/onboard'
      preLoaderRoute: typeof V2OnboardRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/_generalLayout': {
      id: '/v2/_generalLayout'
      path: ''
      fullPath: '/v2'
      preLoaderRoute: typeof V2GeneralLayoutRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/_appv2Layout': {
      id: '/v2/_appv2Layout'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2Appv2LayoutRouteImport
      parentRoute: typeof V2Route
    }
    '/.well-known/farcaster.json': {
      id: '/.well-known/farcaster.json'
      path: '/.well-known/farcaster.json'
      fullPath: '/.well-known/farcaster.json'
      preLoaderRoute: typeof DotwellKnownFarcasterDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_provider': {
      id: '/(app)/_provider'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appProviderRouteRouteImport
      parentRoute: typeof appRoute
    }
    '/v2/_appv2Layout/': {
      id: '/v2/_appv2Layout/'
      path: '/'
      fullPath: '/v2/'
      preLoaderRoute: typeof V2Appv2LayoutIndexRouteImport
      parentRoute: typeof V2Appv2LayoutRoute
    }
    '/v2/quiz/$quizId': {
      id: '/v2/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/v2/quiz/$quizId'
      preLoaderRoute: typeof V2QuizQuizIdRouteImport
      parentRoute: typeof V2Route
    }
    '/v2/_generalLayout/profile': {
      id: '/v2/_generalLayout/profile'
      path: '/profile'
      fullPath: '/v2/profile'
      preLoaderRoute: typeof V2GeneralLayoutProfileRouteImport
      parentRoute: typeof V2GeneralLayoutRoute
    }
    '/v2/_generalLayout/privacy': {
      id: '/v2/_generalLayout/privacy'
      path: '/privacy'
      fullPath: '/v2/privacy'
      preLoaderRoute: typeof V2GeneralLayoutPrivacyRouteImport
      parentRoute: typeof V2GeneralLayoutRoute
    }
    '/v2/_generalLayout/network': {
      id: '/v2/_generalLayout/network'
      path: '/network'
      fullPath: '/v2/network'
      preLoaderRoute: typeof V2GeneralLayoutNetworkRouteImport
      parentRoute: typeof V2GeneralLayoutRoute
    }
    '/v2/_generalLayout/faq': {
      id: '/v2/_generalLayout/faq'
      path: '/faq'
      fullPath: '/v2/faq'
      preLoaderRoute: typeof V2GeneralLayoutFaqRouteImport
      parentRoute: typeof V2GeneralLayoutRoute
    }
    '/v2/_generalLayout/about': {
      id: '/v2/_generalLayout/about'
      path: '/about'
      fullPath: '/v2/about'
      preLoaderRoute: typeof V2GeneralLayoutAboutRouteImport
      parentRoute: typeof V2GeneralLayoutRoute
    }
    '/v2/_appv2Layout/collection': {
      id: '/v2/_appv2Layout/collection'
      path: '/collection'
      fullPath: '/v2/collection'
      preLoaderRoute: typeof V2Appv2LayoutCollectionRouteImport
      parentRoute: typeof V2Appv2LayoutRoute
    }
    '/v2/_appv2Layout/account': {
      id: '/v2/_appv2Layout/account'
      path: '/account'
      fullPath: '/v2/account'
      preLoaderRoute: typeof V2Appv2LayoutAccountRouteImport
      parentRoute: typeof V2Appv2LayoutRoute
    }
    '/api/ai/complete-test': {
      id: '/api/ai/complete-test'
      path: '/api/ai/complete-test'
      fullPath: '/api/ai/complete-test'
      preLoaderRoute: typeof ApiAiCompleteTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(deprecated)/legacy/_app': {
      id: '/(deprecated)/legacy/_app'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof deprecatedLegacyAppRouteImport
      parentRoute: typeof deprecatedLegacyRoute
    }
    '/(app)/_provider/onboard': {
      id: '/(app)/_provider/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof appProviderOnboardRouteImport
      parentRoute: typeof appProviderRouteRoute
    }
    '/(app)/_provider/_general': {
      id: '/(app)/_provider/_general'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appProviderGeneralRouteRouteImport
      parentRoute: typeof appProviderRouteRoute
    }
    '/(app)/_provider/_app': {
      id: '/(app)/_provider/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appProviderAppRouteRouteImport
      parentRoute: typeof appProviderRouteRoute
    }
    '/(deprecated)/legacy/_app/': {
      id: '/(deprecated)/legacy/_app/'
      path: '/'
      fullPath: '/legacy/'
      preLoaderRoute: typeof deprecatedLegacyAppIndexRouteImport
      parentRoute: typeof deprecatedLegacyAppRoute
    }
    '/(app)/_provider/_app/': {
      id: '/(app)/_provider/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appProviderAppIndexRouteImport
      parentRoute: typeof appProviderAppRouteRoute
    }
    '/(app)/_provider/_general/profile': {
      id: '/(app)/_provider/_general/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProviderGeneralProfileRouteImport
      parentRoute: typeof appProviderGeneralRouteRoute
    }
    '/(app)/_provider/_general/privacy': {
      id: '/(app)/_provider/_general/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof appProviderGeneralPrivacyRouteImport
      parentRoute: typeof appProviderGeneralRouteRoute
    }
    '/(app)/_provider/_general/network': {
      id: '/(app)/_provider/_general/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof appProviderGeneralNetworkRouteImport
      parentRoute: typeof appProviderGeneralRouteRoute
    }
    '/(app)/_provider/_general/faq': {
      id: '/(app)/_provider/_general/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof appProviderGeneralFaqRouteImport
      parentRoute: typeof appProviderGeneralRouteRoute
    }
    '/(app)/_provider/_general/about': {
      id: '/(app)/_provider/_general/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof appProviderGeneralAboutRouteImport
      parentRoute: typeof appProviderGeneralRouteRoute
    }
    '/(deprecated)/legacy/_app/collection/': {
      id: '/(deprecated)/legacy/_app/collection/'
      path: '/collection'
      fullPath: '/legacy/collection'
      preLoaderRoute: typeof deprecatedLegacyAppCollectionIndexRouteImport
      parentRoute: typeof deprecatedLegacyAppRoute
    }
    '/(deprecated)/legacy/_app/browse/': {
      id: '/(deprecated)/legacy/_app/browse/'
      path: '/browse'
      fullPath: '/legacy/browse'
      preLoaderRoute: typeof deprecatedLegacyAppBrowseIndexRouteImport
      parentRoute: typeof deprecatedLegacyAppRoute
    }
    '/(deprecated)/legacy/_app/account/': {
      id: '/(deprecated)/legacy/_app/account/'
      path: '/account'
      fullPath: '/legacy/account'
      preLoaderRoute: typeof deprecatedLegacyAppAccountIndexRouteImport
      parentRoute: typeof deprecatedLegacyAppRoute
    }
    '/(app)/_provider/_app/collection/': {
      id: '/(app)/_provider/_app/collection/'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof appProviderAppCollectionIndexRouteImport
      parentRoute: typeof appProviderAppRouteRoute
    }
    '/(app)/_provider/_app/account/': {
      id: '/(app)/_provider/_app/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof appProviderAppAccountIndexRouteImport
      parentRoute: typeof appProviderAppRouteRoute
    }
    '/(deprecated)/legacy/_app/take-quiz/$quizId': {
      id: '/(deprecated)/legacy/_app/take-quiz/$quizId'
      path: '/take-quiz/$quizId'
      fullPath: '/legacy/take-quiz/$quizId'
      preLoaderRoute: typeof deprecatedLegacyAppTakeQuizQuizIdRouteImport
      parentRoute: typeof deprecatedLegacyAppRoute
    }
    '/(app)/_provider/_app/quiz/$quizId': {
      id: '/(app)/_provider/_app/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof appProviderAppQuizQuizIdRouteImport
      parentRoute: typeof appProviderAppRouteRoute
    }
  }
}

interface appProviderAppRouteRouteChildren {
  appProviderAppIndexRoute: typeof appProviderAppIndexRoute
  appProviderAppQuizQuizIdRoute: typeof appProviderAppQuizQuizIdRoute
  appProviderAppAccountIndexRoute: typeof appProviderAppAccountIndexRoute
  appProviderAppCollectionIndexRoute: typeof appProviderAppCollectionIndexRoute
}

const appProviderAppRouteRouteChildren: appProviderAppRouteRouteChildren = {
  appProviderAppIndexRoute: appProviderAppIndexRoute,
  appProviderAppQuizQuizIdRoute: appProviderAppQuizQuizIdRoute,
  appProviderAppAccountIndexRoute: appProviderAppAccountIndexRoute,
  appProviderAppCollectionIndexRoute: appProviderAppCollectionIndexRoute,
}

const appProviderAppRouteRouteWithChildren =
  appProviderAppRouteRoute._addFileChildren(appProviderAppRouteRouteChildren)

interface appProviderGeneralRouteRouteChildren {
  appProviderGeneralAboutRoute: typeof appProviderGeneralAboutRoute
  appProviderGeneralFaqRoute: typeof appProviderGeneralFaqRoute
  appProviderGeneralNetworkRoute: typeof appProviderGeneralNetworkRoute
  appProviderGeneralPrivacyRoute: typeof appProviderGeneralPrivacyRoute
  appProviderGeneralProfileRoute: typeof appProviderGeneralProfileRoute
}

const appProviderGeneralRouteRouteChildren: appProviderGeneralRouteRouteChildren =
  {
    appProviderGeneralAboutRoute: appProviderGeneralAboutRoute,
    appProviderGeneralFaqRoute: appProviderGeneralFaqRoute,
    appProviderGeneralNetworkRoute: appProviderGeneralNetworkRoute,
    appProviderGeneralPrivacyRoute: appProviderGeneralPrivacyRoute,
    appProviderGeneralProfileRoute: appProviderGeneralProfileRoute,
  }

const appProviderGeneralRouteRouteWithChildren =
  appProviderGeneralRouteRoute._addFileChildren(
    appProviderGeneralRouteRouteChildren,
  )

interface appProviderRouteRouteChildren {
  appProviderAppRouteRoute: typeof appProviderAppRouteRouteWithChildren
  appProviderGeneralRouteRoute: typeof appProviderGeneralRouteRouteWithChildren
  appProviderOnboardRoute: typeof appProviderOnboardRoute
}

const appProviderRouteRouteChildren: appProviderRouteRouteChildren = {
  appProviderAppRouteRoute: appProviderAppRouteRouteWithChildren,
  appProviderGeneralRouteRoute: appProviderGeneralRouteRouteWithChildren,
  appProviderOnboardRoute: appProviderOnboardRoute,
}

const appProviderRouteRouteWithChildren =
  appProviderRouteRoute._addFileChildren(appProviderRouteRouteChildren)

interface appRouteChildren {
  appProviderRouteRoute: typeof appProviderRouteRouteWithChildren
}

const appRouteChildren: appRouteChildren = {
  appProviderRouteRoute: appProviderRouteRouteWithChildren,
}

const appRouteWithChildren = appRoute._addFileChildren(appRouteChildren)

interface V2Appv2LayoutRouteChildren {
  V2Appv2LayoutAccountRoute: typeof V2Appv2LayoutAccountRoute
  V2Appv2LayoutCollectionRoute: typeof V2Appv2LayoutCollectionRoute
  V2Appv2LayoutIndexRoute: typeof V2Appv2LayoutIndexRoute
}

const V2Appv2LayoutRouteChildren: V2Appv2LayoutRouteChildren = {
  V2Appv2LayoutAccountRoute: V2Appv2LayoutAccountRoute,
  V2Appv2LayoutCollectionRoute: V2Appv2LayoutCollectionRoute,
  V2Appv2LayoutIndexRoute: V2Appv2LayoutIndexRoute,
}

const V2Appv2LayoutRouteWithChildren = V2Appv2LayoutRoute._addFileChildren(
  V2Appv2LayoutRouteChildren,
)

interface V2GeneralLayoutRouteChildren {
  V2GeneralLayoutAboutRoute: typeof V2GeneralLayoutAboutRoute
  V2GeneralLayoutFaqRoute: typeof V2GeneralLayoutFaqRoute
  V2GeneralLayoutNetworkRoute: typeof V2GeneralLayoutNetworkRoute
  V2GeneralLayoutPrivacyRoute: typeof V2GeneralLayoutPrivacyRoute
  V2GeneralLayoutProfileRoute: typeof V2GeneralLayoutProfileRoute
}

const V2GeneralLayoutRouteChildren: V2GeneralLayoutRouteChildren = {
  V2GeneralLayoutAboutRoute: V2GeneralLayoutAboutRoute,
  V2GeneralLayoutFaqRoute: V2GeneralLayoutFaqRoute,
  V2GeneralLayoutNetworkRoute: V2GeneralLayoutNetworkRoute,
  V2GeneralLayoutPrivacyRoute: V2GeneralLayoutPrivacyRoute,
  V2GeneralLayoutProfileRoute: V2GeneralLayoutProfileRoute,
}

const V2GeneralLayoutRouteWithChildren = V2GeneralLayoutRoute._addFileChildren(
  V2GeneralLayoutRouteChildren,
)

interface V2RouteChildren {
  V2Appv2LayoutRoute: typeof V2Appv2LayoutRouteWithChildren
  V2GeneralLayoutRoute: typeof V2GeneralLayoutRouteWithChildren
  V2OnboardRoute: typeof V2OnboardRoute
  V2QuizQuizIdRoute: typeof V2QuizQuizIdRoute
}

const V2RouteChildren: V2RouteChildren = {
  V2Appv2LayoutRoute: V2Appv2LayoutRouteWithChildren,
  V2GeneralLayoutRoute: V2GeneralLayoutRouteWithChildren,
  V2OnboardRoute: V2OnboardRoute,
  V2QuizQuizIdRoute: V2QuizQuizIdRoute,
}

const V2RouteWithChildren = V2Route._addFileChildren(V2RouteChildren)

interface deprecatedLegacyAppRouteChildren {
  deprecatedLegacyAppIndexRoute: typeof deprecatedLegacyAppIndexRoute
  deprecatedLegacyAppTakeQuizQuizIdRoute: typeof deprecatedLegacyAppTakeQuizQuizIdRoute
  deprecatedLegacyAppAccountIndexRoute: typeof deprecatedLegacyAppAccountIndexRoute
  deprecatedLegacyAppBrowseIndexRoute: typeof deprecatedLegacyAppBrowseIndexRoute
  deprecatedLegacyAppCollectionIndexRoute: typeof deprecatedLegacyAppCollectionIndexRoute
}

const deprecatedLegacyAppRouteChildren: deprecatedLegacyAppRouteChildren = {
  deprecatedLegacyAppIndexRoute: deprecatedLegacyAppIndexRoute,
  deprecatedLegacyAppTakeQuizQuizIdRoute:
    deprecatedLegacyAppTakeQuizQuizIdRoute,
  deprecatedLegacyAppAccountIndexRoute: deprecatedLegacyAppAccountIndexRoute,
  deprecatedLegacyAppBrowseIndexRoute: deprecatedLegacyAppBrowseIndexRoute,
  deprecatedLegacyAppCollectionIndexRoute:
    deprecatedLegacyAppCollectionIndexRoute,
}

const deprecatedLegacyAppRouteWithChildren =
  deprecatedLegacyAppRoute._addFileChildren(deprecatedLegacyAppRouteChildren)

interface deprecatedLegacyRouteChildren {
  deprecatedLegacyAppRoute: typeof deprecatedLegacyAppRouteWithChildren
}

const deprecatedLegacyRouteChildren: deprecatedLegacyRouteChildren = {
  deprecatedLegacyAppRoute: deprecatedLegacyAppRouteWithChildren,
}

const deprecatedLegacyRouteWithChildren =
  deprecatedLegacyRoute._addFileChildren(deprecatedLegacyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  appRoute: appRouteWithChildren,
  DotwellKnownFarcasterDotjsonRoute: DotwellKnownFarcasterDotjsonRoute,
  V2Route: V2RouteWithChildren,
  deprecatedLegacyRoute: deprecatedLegacyRouteWithChildren,
  ApiAiCompleteTestRoute: ApiAiCompleteTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
